### ISSUE TITLE
Count of pending visits is broken

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#274]
Marked a visit as happened, but the count on the homepage didn't change. In general as we moved forward and backward in time it seemed broken. E.g., when visits were > 7 days overdue, they're not in the list but still impact count

**Comment by tperrier** [comment]
I can't replicated this? Everything seems to work well on my computer. This
might be an issue with timezones? There is a issue with the visits where if
you go back in time a visit marked as seen will not reappear - I figure
since time will not go backwards this is ok.

However, if the Home visit count and Visits page displayed visits are not
matching up that is bug.

**Comment by bderenzi** [comment]
Just pulled the latest changes, refreshed the DB and was able to replicate the issue. Steps I took:
1. pulled latest data
2. python manage.py reset_db -P 15
3. gulp
4. ./manage.py runserver

Then once the app was up:
1. Login; 0 new visits
2. Press the forward date once: 1 new visit
3. Press the forward date a second time: 2 new visits listed
   ![mainmenu](https://cloud.githubusercontent.com/assets/94682/10563181/071350fc-7587-11e5-949d-c8b48d6a0bbc.png)
4. Go to pending vistis page; only one visit is listed. 
   ![visits](https://cloud.githubusercontent.com/assets/94682/10563182/0713bba0-7587-11e5-9451-a0cd6c5fd04f.png)
