### ISSUE TITLE
recording calls has 2 different modals

### ISSUE THREAD

**Issue by bderenzi** [tperrier/mwachx#299]
Why is the record call from the pending page different from the record call from the participant page. As a user that suggests that there are 2 different processes I'm doing. I might even not do one that is convenient because I think I have to go do the other one in order to achieve the correct result.

**Comment by tperrier** [comment]
I think there is a good reason for this because yes, there are two different process.

## Record Call Page

Calls from here can **only** be outgoing so there is no need to ask if it is Incoming. There is only a length if the phone call was answered.

## Participant Phone Call Modal

Calls from here can **either** be incoming or outgoing.  Right now the default is outgoing but I think I should change the default to incoming. 

I don't think it makes any sense to include incoming calls on the Record Call page since these are all outgoing scheduled calls.  However, I'm willing to be convinced otherwise.
